#!/usr/bin/env python3
"""Run the sequence aligner over a corpus and compare every artifact with a stored tree.

    compare_aligners.py --source-files DIR --source-metadata FILE [--target-files DIR
        --target-metadata FILE] --reference DIR [--threads N] [--workdir DIR]
        [--run-cwd DIR] [--param name=value]...
    compare_aligners.py --fixtures [--threads N]          # the synthetic corpora here
    compare_aligners.py --fixtures --binary [--threads N] # ... with a binary ngram index

A reference is stored output, not a second implementation. The fixtures keep theirs in
fixtures/<name>/reference; regenerate them with fixtures/record_references.py whenever the
matcher changes, and say in the commit why the records moved. Corpus-scale references are
under /disk1/shared/text-pair-validation.

--run-source-files / --run-target-files point the fresh run at a different ngram directory
from the reference's, which is how a converted (binary) index is checked against a
reference built from the JSON original.

Compared: chunk file names, every JSON record as a sorted multiset (and per chunk, byte
for byte), count.txt, duplicate_files.csv as a sorted multiset, and alignment_config.ini
apart from outputPath. Exits non-zero on any difference and prints the first record that
differs.

A mismatch is EXPECTED on any corpus where a document's sort value does not parse as an
integer: documents are ordered by a total sort key in which such values sort last, so a
reference built before that behaviour, or from a different directory listing, can swap
which document of a pair is the source. The run reports this as mismatch_expected, and
because the matcher is symmetric those records should then be exact mirrors of each other.
"""
import argparse
import glob
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
from collections import Counter
from concurrent.futures import ProcessPoolExecutor

import lz4.frame
import orjson

from textpair.sequence_alignment.aligner import docorder
from textpair.sequence_alignment.aligner.gotext import load_metadata
from textpair.sequence_alignment.tests.check_direction_flips import flip

FIXTURES = ("no_byte_range", "non_string_meta", "missing_text", "no_metadata")
# Reference trees are stored output, not a second implementation: the fixtures carry
# theirs in fixtures/<name>/reference, regenerated by --record when the matcher changes.
CANON = orjson.OPT_SORT_KEYS


def digest(line):
    return hashlib.sha1(orjson.dumps(orjson.loads(line), option=CANON)).digest()


def read_chunk(path):
    if not path:
        return b"", []
    with lz4.frame.open(path, "rb") as handle:
        raw = handle.read()
    return raw, [digest(line) for line in raw.splitlines() if line.strip()]


def compare_chunk(job):
    name, reference_path, current_path = job
    reference_raw, reference_digests = read_chunk(reference_path)
    current_raw, current_digests = read_chunk(current_path)
    return name, reference_raw == current_raw, reference_digests, current_digests


def chunks(results_dir):
    """Chunk files, wherever the aligner left them (a batched run keeps result_chunks)."""
    found = {}
    for path in glob.glob(os.path.join(results_dir, "result_batches", "**", "*.lz4"),
                          recursive=True):
        found[os.path.basename(path)] = path
    return found


def first_difference(reference_chunks, current_chunks, only_reference, only_current):
    """The first record, in chunk-name order, whose digest is unique to one side."""
    out = {}
    for label, source, wanted in (("reference", reference_chunks, only_reference),
                                  ("current", current_chunks, only_current)):
        for name in sorted(source):
            with lz4.frame.open(source[name], "rb") as handle:
                for line in handle.read().splitlines():
                    if line.strip() and digest(line) in wanted:
                        out[label] = {"chunk": name, "record": orjson.loads(line)}
                        break
            if label in out:
                break
    if "reference" in out and "current" in out:
        was, now = out["reference"]["record"], out["current"]["record"]
        out["differing_fields"] = sorted(k for k in set(was) | set(now)
                                         if was.get(k) != now.get(k))
    return out


def read_text(path):
    with open(path, encoding="utf8") as handle:
        return handle.read()


def unparseable_sort_values(ngrams_dir, metadata_path, sort_by, run_cwd):
    """Documents whose sort value does not parse as an integer, and those with no
    metadata entry at all: where a stored reference and a fresh run can order the corpus
    differently, and so swap which document of a pair is the source."""
    if not ngrams_dir or not metadata_path or not sort_by:
        return None
    root = run_cwd or "."
    metadata = load_metadata(os.path.join(root, metadata_path))
    if docorder.sort_mode(metadata, sort_by) != docorder.NUMERIC:
        return None
    doc_ids = [docorder.doc_id_of(name)
               for name in os.listdir(os.path.join(root, ngrams_dir))]
    return sum(docorder.parse_int(metadata.get(doc, {}).get(sort_by, "")) is None
               for doc in doc_ids)


def sort_expectation(args, params):
    sort_by = params.get("sort_by", "year")
    counts = [unparseable_sort_values(files, metadata, sort_by, args.run_cwd)
              for files, metadata in ((args.source_files, args.source_metadata),
                                      (args.target_files, args.target_metadata))]
    return {"sort_by": sort_by,
            "n_unparseable_sort_values": [count for count in counts if count is not None],
            "mismatch_expected": any(count for count in counts)}


def mirrors(reference_chunks, current_chunks, only_reference, only_current):
    """Whether the records unique to each run are the other's with source and target
    exchanged, meaning the two runs found the same alignments in opposite directions.

    The matcher is symmetric, so a pure document-order difference should mirror exactly
    apart from the tie `test_matcher_symmetry.py` documents: two candidate predecessors
    at (di, dj) and (dj, di) with equal chain length, which moves a passage's start by a
    few ngrams. This stays advisory rather than required for that reason."""
    found = {"reference": set(), "current": set()}
    for label, source, wanted in (("reference", reference_chunks, only_reference),
                                  ("current", current_chunks, only_current)):
        for name in sorted(source):
            with lz4.frame.open(source[name], "rb") as handle:
                for line in handle.read().splitlines():
                    if line.strip() and digest(line) in wanted:
                        record = orjson.loads(line)
                        if label == "reference":
                            record = flip(record)
                        found[label].add(
                            hashlib.sha1(orjson.dumps(record, option=CANON)).digest())
    return found["reference"] == found["current"]


def compare(reference_dir, current_dir, workers, expectation=None):
    reference_chunks, current_chunks = chunks(reference_dir), chunks(current_dir)
    result = dict(expectation or {})
    result.update({
        "n_chunks_reference": len(reference_chunks),
        "n_chunks_current": len(current_chunks),
        "chunk_names_identical": sorted(reference_chunks) == sorted(current_chunks),
    })
    if not result["chunk_names_identical"]:
        result["chunks_only_reference"] = sorted(set(reference_chunks) - set(current_chunks))[:20]
        result["chunks_only_currentthon"] = sorted(set(current_chunks) - set(reference_chunks))[:20]

    jobs = [(name, reference_chunks.get(name), current_chunks.get(name))
            for name in sorted(set(reference_chunks) | set(current_chunks))]
    reference_counts, current_counts = Counter(), Counter()
    identical_bytes = 0
    if workers > 1 and len(jobs) > 1:
        with ProcessPoolExecutor(workers) as pool:
            results = pool.map(compare_chunk, jobs, chunksize=16)
            for _name, same_bytes, reference_digests, current_digests in results:
                identical_bytes += same_bytes
                reference_counts.update(reference_digests)
                current_counts.update(current_digests)
    else:
        for job in jobs:
            _name, same_bytes, reference_digests, current_digests = compare_chunk(job)
            identical_bytes += same_bytes
            reference_counts.update(reference_digests)
            current_counts.update(current_digests)
    result["n_records_reference"] = sum(reference_counts.values())
    result["n_records_current"] = sum(current_counts.values())
    result["records_identical_multiset"] = reference_counts == current_counts
    result["chunks_byte_identical"] = f"{identical_bytes}/{len(jobs)}"
    if not result["records_identical_multiset"]:
        only_reference = set((reference_counts - current_counts).elements())
        only_current = set((current_counts - reference_counts).elements())
        result["records_only_reference"] = len(only_reference)
        result["records_only_currentthon"] = len(only_current)
        result["first_difference"] = first_difference(reference_chunks, current_chunks, only_reference, only_current)
        if result.get("mismatch_expected"):
            result["records_identical_as_direction_flips"] = mirrors(
                reference_chunks, current_chunks, only_reference, only_current)

    reference_count = read_text(os.path.join(reference_dir, "count.txt"))
    current_count = read_text(os.path.join(current_dir, "count.txt"))
    result["count_txt"] = [reference_count, current_count]
    result["count_txt_identical"] = reference_count == current_count

    reference_dups = read_text(os.path.join(reference_dir, "duplicate_files.csv")).splitlines()
    current_dups = read_text(os.path.join(current_dir, "duplicate_files.csv")).splitlines()
    result["n_duplicates_reference"] = max(0, len(reference_dups) - 1)
    result["n_duplicates_current"] = max(0, len(current_dups) - 1)
    result["duplicates_identical_multiset"] = (reference_dups[:1] == current_dups[:1]
                                               and sorted(reference_dups[1:]) == sorted(current_dups[1:]))
    if not result["duplicates_identical_multiset"]:
        result["duplicates_only_reference"] = sorted(set(reference_dups) - set(current_dups))[:5]
        result["duplicates_only_current"] = sorted(set(current_dups) - set(reference_dups))[:5]

    def config(path):
        return [line for line in read_text(path).splitlines()
                if not line.startswith("outputPath:")]

    reference_config = config(os.path.join(reference_dir, "alignment_config.ini"))
    current_config = config(os.path.join(current_dir, "alignment_config.ini"))
    result["config_identical"] = reference_config == current_config
    if not result["config_identical"]:
        result["config_diff"] = [[a, b] for a, b in zip(reference_config, current_config)
                                 if a != b]
    result["PASS"] = all(result[key] for key in ("chunk_names_identical",
                                                 "records_identical_multiset",
                                                 "count_txt_identical",
                                                 "duplicates_identical_multiset",
                                                 "config_identical"))
    if not result["PASS"] and result.get("mismatch_expected"):
        result["note"] = ("EXPECTED: some of this corpus' sort values do not parse, so "
                          "the two aligners order documents differently by design; chunk "
                          "names, and the alignments involving those documents, differ "
                          "with it. check_direction_flips.py characterises the change.")
    return result


def flags(args, params, output_path, source_files="", target_files=""):
    source_files = source_files or args.source_files
    target_files = target_files or args.target_files
    out = [f"--output_path={output_path}", f"--threads={args.threads}",
           f"--source_files={source_files}", f"--source_metadata={args.source_metadata}"]
    if target_files:
        out.append(f"--target_files={target_files}")
    if args.target_metadata:
        out.append(f"--target_metadata={args.target_metadata}")
    return out + [f"--{key}={value}" for key, value in params.items()]


def run_pair(args, params):
    workdir = os.path.abspath(args.workdir)
    os.makedirs(workdir, exist_ok=True)
    current_dir = os.path.join(workdir, "current")
    if not args.current_results:
        shutil.rmtree(current_dir, ignore_errors=True)
    env = dict(os.environ, OPENBLAS_NUM_THREADS="1")
    env.setdefault("TEXTPAIR_NUMBA_CACHE_DIR", os.path.join(workdir, "numba_cache"))
    if args.current_results:
        current_dir = os.path.abspath(args.current_results)
    if not args.reference:
        raise SystemExit("no reference to compare against: pass --reference a stored "
                         "output tree.")
    reference_dir = os.path.abspath(args.reference)
    if not args.current_results:
        print(f"--- aligner -> {current_dir}", flush=True)
        subprocess.run([sys.executable, "-m", "textpair.sequence_alignment.aligner"]
                       + flags(args, params, current_dir, args.run_source_files,
                               args.run_target_files),
                       cwd=args.run_cwd, check=True, env=env, stdout=subprocess.DEVNULL)
    return reference_dir, current_dir


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--source-files", default="")
    parser.add_argument("--source-metadata", default="")
    parser.add_argument("--target-files", default="")
    parser.add_argument("--target-metadata", default="")
    parser.add_argument("--threads", type=int, default=4)
    parser.add_argument("--workdir", help="the fresh run's output tree, never in the repo",
                        default=os.path.join(tempfile.gettempdir(), "textpair_aligner_check"))
    parser.add_argument("--reference", default="",
                        help="stored output tree to compare against")
    parser.add_argument("--current-results", default="",
                        help="reuse an existing Python output tree")
    parser.add_argument("--run-cwd", default=None, help="cwd for the aligner")
    parser.add_argument("--run-source-files", default="",
                        help="ngram directory for the Python run only, e.g. a binary index")
    parser.add_argument("--run-target-files", default="")
    parser.add_argument("--param", action="append", default=[], metavar="NAME=VALUE",
                        help="matching parameter for the run")
    parser.add_argument("--compare-workers", type=int, default=8)
    parser.add_argument("--fixtures", action="store_true",
                        help="run every synthetic fixture corpus in fixtures/")
    parser.add_argument("--binary", action="store_true",
                        help="with --fixtures: convert each index to binary for the Python run")
    args = parser.parse_args(argv)
    params = dict(item.split("=", 1) for item in args.param)

    if args.fixtures:
        here = os.path.dirname(os.path.abspath(__file__))
        failures, expected = [], []
        for name in FIXTURES:
            print(f"\n=== fixture {name} ===", flush=True)
            fixture = argparse.Namespace(**vars(args))
            fixture.source_files = "ngrams"
            fixture.source_metadata = "metadata/metadata.json"
            fixture.target_files = fixture.target_metadata = ""
            fixture.run_cwd = os.path.join(here, "fixtures", name)
            fixture.workdir = os.path.join(os.path.abspath(args.workdir), name)
            fixture.current_results = ""
            fixture.reference = os.path.join(fixture.run_cwd, "reference")
            if args.binary:
                from textpair.sequence_alignment.ngram_binary import convert_directory

                fixture.run_source_files = os.path.join(fixture.workdir, "ngrams_binary")
                shutil.rmtree(fixture.run_source_files, ignore_errors=True)
                convert_directory(os.path.join(fixture.run_cwd, "ngrams"),
                                  fixture.run_source_files, args.threads)
            result = compare(*run_pair(fixture, params), args.compare_workers,
                             sort_expectation(fixture, params))
            print(json.dumps(result, indent=1, ensure_ascii=False))
            if result["PASS"]:
                continue
            if result.get("records_identical_as_direction_flips"):
                expected.append(name)
            else:
                failures.append(name)
        if expected:
            print("\nEXPECTED mismatches, records are exact direction flips:", *expected)
        if failures:
            print("\nFAILED fixtures:", *failures)
        else:
            print("\nNo fixture failed")
        return 1 if failures else 0

    if not args.source_files or not args.source_metadata:
        parser.error("--source-files and --source-metadata are required")
    result = compare(*run_pair(args, params), args.compare_workers,
                     sort_expectation(args, params))
    print(json.dumps(result, indent=1, ensure_ascii=False))
    return 0 if result["PASS"] else 1


if __name__ == "__main__":
    sys.exit(main())
