[WEB_APP]
## Directory where generated web apps are written; irrelevant if you always pass --skip_web_app
web_app_path = /var/www/html/text-pair
## Base URL where the TextPAIR API is served
api_server = http://localhost/text-pair-api

[DATABASE]
database_name = textpair
database_user = textpair
database_password =
